name: lint_and_style

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: false
    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
    - name: Install Mamba
      run: conda install -n base -c conda-forge mamba
    - name: Create Environment with Mamba
      run: mamba env create -f env.yml
    - name: Activate Environment
      run: echo "conda activate lint_and_style" >> $GITHUB_ENV
    - name: Run Pre-Commit
      uses: pre-commit/action@v3.0.1

  pylint:
    runs-on: ubuntu-latest
    needs: pre-commit
    continue-on-error: true
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
    - name: Install Mamba
      run: conda install -n base -c conda-forge mamba
    - name: Create Environment with Mamba
      run: mamba env create -f env.yml
    - name: Activate Environment
      run: echo "conda activate lint_and_style" >> $GITHUB_ENV
    - name: Run Pre-Commit with Pylint
      uses: pre-commit/action@v3.0.1
      with:
        extra_args: --hook-stage manual pylint-all --all-files