name: lint_and_style

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: env.yml
        activate-environment: lint_and_style
        auto-activate-base: false
    - uses: pre-commit/action@v3.0.1

  pylint:
    runs-on: ubuntu-latest
    needs: pre-commit
    continue-on-error: true
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: env.yml
        activate-environment: lint_and_style
        auto-activate-base: false
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --hook-stage manual pylint-all --all-files
